"""initial

Revision ID: ba7697b8affd
Revises: 
Create Date: 2026-06-27 23:13:32.932572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7697b8affd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('matricula', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('curso', sa.String(), nullable=False),
    sa.Column('ano_ingresso', sa.Integer(), nullable=False),
    sa.Column('semestre_ingresso', sa.Integer(), nullable=False),
    sa.Column('quantidade_creditos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('matricula')
    )
    op.create_table('curriculos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('curso', sa.String(), nullable=False),
    sa.Column('ano_vigencia', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disciplinas',
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=False),
    sa.Column('carga_horaria', sa.Integer(), nullable=False),
    sa.Column('tipo_disciplina', sa.Enum('OBRIGATORIA', 'OPTATIVA', name='tipodisciplina'), nullable=False),
    sa.Column('departamento', sa.Enum('DI', 'DMAT', 'DEE', 'OUTRO', name='departamento'), nullable=False),
    sa.Column('periodo_sugerido', sa.Integer(), nullable=True),
    sa.Column('periodo_oferta', sa.Enum('PAR', 'IMPAR', 'AMBOS', name='periodooferta'), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('curriculo_disciplinas',
    sa.Column('curriculo_id', sa.Integer(), nullable=False),
    sa.Column('codigo_disciplina', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['codigo_disciplina'], ['disciplinas.codigo'], ),
    sa.ForeignKeyConstraint(['curriculo_id'], ['curriculos.id'], ),
    sa.PrimaryKeyConstraint('curriculo_id', 'codigo_disciplina')
    )
    op.create_table('historicos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('matricula', sa.String(), nullable=False),
    sa.Column('cr', sa.Float(), nullable=True),
    sa.Column('creditos_totais', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['matricula'], ['alunos.matricula'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prerequisitos',
    sa.Column('codigo_disciplina', sa.String(), nullable=False),
    sa.Column('codigo_prereq', sa.String(), nullable=False),
    sa.Column('bloco', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['codigo_disciplina'], ['disciplinas.codigo'], ),
    sa.ForeignKeyConstraint(['codigo_prereq'], ['disciplinas.codigo'], ),
    sa.PrimaryKeyConstraint('codigo_disciplina', 'codigo_prereq')
    )
    op.create_table('historico_disciplinas',
    sa.Column('historico_id', sa.Integer(), nullable=False),
    sa.Column('codigo_disciplina', sa.String(), nullable=False),
    sa.Column('media', sa.Float(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['codigo_disciplina'], ['disciplinas.codigo'], ),
    sa.ForeignKeyConstraint(['historico_id'], ['historicos.id'], ),
    sa.PrimaryKeyConstraint('historico_id', 'codigo_disciplina')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_disciplinas')
    op.drop_table('prerequisitos')
    op.drop_table('historicos')
    op.drop_table('curriculo_disciplinas')
    op.drop_table('disciplinas')
    op.drop_table('curriculos')
    op.drop_table('alunos')
    # ### end Alembic commands ###
